kind: Deployment
apiVersion: apps/v1
metadata:
  name: group13
  namespace: group13
  labels:
    app: group13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group13
  template:
    metadata:
      labels:
        app: group13
    spec:
      containers:
      - name: group13
        image: ebram100/dierentuinn-name:latest
        ports:
        - name: web
          containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: registry-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: group13
  namespace: group13
spec:
  ports:
    - name: web
      port: 80
      targetPort: web
  selector:
    app: group13
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: group13route
  namespace: group13
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`13.web.dops.tech`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: group13
      port: 80
  tls:
    certResolver: myresolver
