






workflow file:

name: docker building

on:
  push:
    branches-ignore:
    -  'master'
  pull_request:
    branches-ignore:
    -  'master'

jobs:
  build_and_publish:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file Dierentuinn/Dockerfile --tag dierentuinn-name:$(date +%s)

    - name: Run tests and build       
      run: | 
          docker run --rm \ 
          -v ${{ github.workspace }}:/workspace \   
          -w /workspace \ 
          mcr.microsoft.com/dotnet/sdk:8.0 \ 
          bash -c "dotnet restore && dotnet build --no-restore && dotnet test --no-build --verbosity normal"

        
      

      
